### ISSUE TITLE
[Question] will it work in MicroPython?

### ISSUE THREAD

**Issue by felixmosh** [zhufucdev/gdey075z08_driver#1]
Hi, is this driver will work with microPython?

**Comment by zhufucdev** [comment]
I don't think it will

**Comment by felixmosh** [comment]
Wow, thank you for the quick response 🙂 

What is the missing part?

**Comment by zhufucdev** [comment]
https://pypi.org/project/RPi.GPIO/

**Comment by felixmosh** [comment]
Can we somehow extract only the driver, without the gpio managment? (I'll try)
